pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.gradle
      - ./ui/node_modules
    volumes:
      - cache:/cache

  build:
    image: openems-build:latest
    environment:
      - GRADLE_USER_HOME=/drone/.gradle
    commands:
      - ./gradlew build
      - ./gradlew resolve.BackendApp
      - git diff --exit-code io.openems.backend.application/BackendApp.bndrun
      - ./gradlew resolve.EdgeApp
      - git diff --exit-code io.openems.edge.application/EdgeApp.bndrun
      - ./gradlew buildUiForEdge --continue

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.gradle
      - ./ui/node_modules
    volumes:
      - cache:/cache